const KEY = 'crm_workflow_v3';
const stages = ['New', 'Contact Attempted', 'RNR 1', 'RNR 2', 'RNR 3', 'Connected', 'Interested', 'Follow-up', 'Site Visit Scheduled', 'Site Visit Completed', 'Negotiation', 'Booking/Closed Won', 'Not Interested', 'Lost'];
const check = (ok, message) => { if (!ok) throw new Error(message); };
const now = () => new Date().toISOString();
function seed() {
  const users = ['Admin', 'Manager', 'Sales_Exec', 'Telecaller'].map((role, i) => ({ id: i + 1, role, name: ['Rajesh Kumar', 'Priya Sharma', 'Amit Verma', 'Vikram Singh'][i], email: ['admin', 'manager', 'sales1', 'tele'][i] + '@democrm.com', is_active: 1, password: 'Password123!' }));
  let old = []; try { old = JSON.parse(localStorage.getItem('crm_demo_leads') || '[]'); } catch {}
  const leads = (old.length ? old : [{ id: 101, name: 'Ananya Krishnan', phone: '9000000101', budget: 18000000, stage: 'New' }, { id: 102, name: 'Rohan Mehta', phone: '9000000102', budget: 24000000, stage: 'New' }]).map((l, i) => ({ ...l, assigned_user_id: i % 2 ? 3 : 4, project_id: 1, source_id: 1, status: 'Active', created_at: l.created_at || now() }));
  return { seq: Math.max(1000, ...leads.map(l => l.id)), users, leads, activities: [], followups: [], siteVisits: [], negotiations: [], bookings: [], notifications: [], company: { id: 1, name: 'Demo CRM', email: 'hello@example.com' }, projects: [{ id: 1, name: 'Skyline Residences', location: 'Bengaluru', total_units: 120, status: 'Active' }], sources: [{ id: 1, name: 'Website', type: 'digital', is_active: 1 }] };
}
export function workflow(endpoint, method, body, session) {
  const db = JSON.parse(localStorage.getItem(KEY) || 'null') || seed();
  const save = (result = { success: true, message: 'Saved' }) => { localStorage.setItem(KEY, JSON.stringify(db)); return result; };
  const uid = () => ++db.seq;
  const url = new URL(endpoint, 'https://demo.invalid'); const p = url.pathname; const q = url.searchParams;
  const safe = u => { const { password, ...rest } = u; return { ...rest, company_id: 1, company: db.company }; };
  if (p === '/auth/login') { const u = db.users.find(u => u.email.toLowerCase() === body.email.trim().toLowerCase() && u.password === body.password && u.is_active); check(u, 'Invalid credentials or inactive account.'); return save({ token: 'demo-session', user: safe(u) }); }
  const actor = db.users.find(u => u.id === session?.id && u.is_active); check(actor, 'Please sign in again.');
  const manager = ['Admin', 'Manager'].includes(actor.role); const sales = manager || actor.role === 'Sales_Exec';
  const visible = l => manager || l.assigned_user_id === actor.id;
  const get = id => { const l = db.leads.find(l => l.id === Number(id)); check(l && visible(l), 'This lead is not assigned to you.'); return l; };
  const decorate = l => ({ ...l, assigned_user_name: db.users.find(u => u.id === l.assigned_user_id)?.name, project_name: db.projects.find(v => v.id === l.project_id)?.name, source_name: db.sources.find(v => v.id === l.source_id)?.name });
  const related = key => db[key].filter(r => db.leads.some(l => l.id === r.lead_id && visible(l))).map(r => { const l = decorate(get(r.lead_id)); return { ...r, lead_name: l.name, lead_phone: l.phone, project_name: l.project_name, user_name: l.assigned_user_name }; });
  const event = (l, title, description = '') => { l.updated_at = now(); db.activities.unshift({ id: uid(), lead_id: l.id, lead_name: l.name, type: 'NOTE', title, description, user_name: actor.name, created_at: now(), action: title, entity_type: 'Lead', entity_id: l.id }); };
  const stage = (l, s) => { check(stages.includes(s), 'Choose a valid stage.'); l.stage = s; l.status = s === 'Booking/Closed Won' ? 'Won' : ['Lost', 'Not Interested'].includes(s) ? 'Lost' : 'Active'; };
  const assign = (l, id) => { check(manager, 'Only managers and admins can assign leads.'); const u = db.users.find(u => u.id === Number(id) && u.is_active); check(u, 'Select an active representative.'); l.assigned_user_id = u.id; event(l, 'Lead assigned', `${u.name} (${u.role})`); db.notifications.unshift({ id: uid(), user_id: u.id, title: 'Lead assigned', body: l.name, lead_id: l.id, is_read: 0, created_at: now() }); };
  const schedule = (l, date, type, remarks) => { check(date && Number.isFinite(Date.parse(date)), 'Select a valid follow-up date.'); db.followups.unshift({ id: uid(), lead_id: l.id, scheduled_at: date, action_type: type || 'Call', remarks, status: 'Pending' }); l.next_followup_at = date; event(l, 'Follow-up scheduled', `${date} • ${remarks || ''}`); };
  if (p === '/auth/users') { if (method === 'GET') return save({ users: db.users.map(safe) }); check(actor.role === 'Admin', 'Only admins can create users.'); check(body.name && body.email && !db.users.some(u => u.email === body.email), 'Use a unique email and name.'); check(['Admin', 'Manager', 'Sales_Exec', 'Telecaller'].includes(body.role), 'Invalid role.'); db.users.push({ ...body, id: uid(), is_active: 1, password: body.password || 'Password123!' }); return save(); }
  let m = p.match(/^\/auth\/users\/(\d+)\/toggle-active$/);
  if (m) { check(actor.role === 'Admin' && Number(m[1]) !== actor.id, 'Only admins can update another user.'); const u = db.users.find(u => u.id === Number(m[1])); check(u, 'User not found.'); u.is_active = u.is_active ? 0 : 1; return save(); }
  if (p.startsWith('/settings/')) { const key = { company: 'company', projects: 'projects', 'lead-sources': 'sources', 'audit-logs': 'activities' }[p.split('/')[2]]; check(key, 'Unknown setting.'); if (method !== 'GET' || ['company', 'activities'].includes(key)) check(manager, 'Manager access required.'); if (method === 'GET') return save({ [key === 'activities' ? 'auditLogs' : key]: db[key] }); if (key === 'company') Object.assign(db.company, body); else { check(body.name, 'Name is required.'); db[key].push({ ...body, id: uid(), is_active: 1, status: 'Active', total_units: body.totalUnits, price_range: body.priceRange }); } return save(); }
  if (p === '/leads') {
    if (method === 'POST') { check(body.name?.trim() && body.phone?.trim(), 'Name and phone are required.'); const duplicate = db.leads.find(l => l.phone.replace(/\D/g, '') === body.phone.replace(/\D/g, '')); if (duplicate) { check(visible(duplicate), 'An existing lead has this phone. Contact your manager.'); event(duplicate, 'Repeat enquiry', 'Another enquiry received'); return save({ isDuplicate: true }); } const l = { ...body, id: uid(), stage: 'New', status: 'Active', assigned_user_id: manager ? null : actor.id, project_id: 1, source_id: 1, created_at: now() }; db.leads.unshift(l); event(l, 'Lead received'); return save({ lead: decorate(l), isDuplicate: false }); }
    const leads = db.leads.filter(visible).filter(l => (!q.get('stage') || l.stage === q.get('stage')) && (!q.get('project_id') || l.project_id === Number(q.get('project_id'))) && (!q.get('source_id') || l.source_id === Number(q.get('source_id'))) && (q.get('unassigned') !== 'true' || !l.assigned_user_id) && (!q.get('search') || `${l.name} ${l.phone} ${l.email}`.toLowerCase().includes(q.get('search').toLowerCase()))).map(decorate); return save({ leads, total: leads.length, stages, totalPages: 1 });
  }
  if (p.startsWith('/leads/bulk-')) { check(manager, 'Manager access required.'); body.leadIds.map(get).forEach(l => p.endsWith('assign') ? assign(l, body.assignedUserId) : (stage(l, body.stage), event(l, 'Stage changed', body.stage))); return save(); }
  m = p.match(/^\/leads\/(\d+)(?:\/(.+))?$/);
  if (m) { const l = get(m[1]); const action = m[2];
    if (!action && method === 'GET') return save({ lead: decorate(l), activities: db.activities.filter(a => a.lead_id === l.id), ...Object.fromEntries(['followups', 'siteVisits', 'negotiations', 'bookings'].map(k => [k, related(k).filter(r => r.lead_id === l.id)])), stages, callOutcomes: ['Connected', 'RNR', 'Busy', 'Interested', 'Visit agreed', 'Visit declined', 'Follow-up Scheduled', 'Not Interested'] });
    if (action === 'reassign') assign(l, body.assignedUserId);
    else if (action === 'notes') { check(body.note?.trim(), 'Write a note.'); event(l, 'Note added', body.note); }
    else if (action === 'stage') { check(body.stage !== 'Booking/Closed Won', 'Close a negotiation to record the booking value.'); stage(l, body.stage); event(l, 'Stage changed', `${body.stage} • ${body.remarks || ''}`); }
    else if (action === 'call-outcome') { check(l.assigned_user_id, 'Assign the lead before recording feedback.'); if (body.outcome === 'RNR') { l.rnr_count = Math.min(3, (l.rnr_count || 0) + 1); stage(l, `RNR ${l.rnr_count}`); } else stage(l, ({ 'Visit agreed': 'Interested', 'Visit declined': 'Follow-up', Busy: 'Contact Attempted', 'Follow-up Scheduled': 'Follow-up' })[body.outcome] || body.outcome); l.last_outcome = body.outcome; l.last_feedback = body.remarks; event(l, `Call: ${body.outcome}`, body.remarks); if (body.nextFollowupDate) schedule(l, body.nextFollowupDate, 'Call', body.remarks); }
    else throw new Error('Unsupported lead action.'); return save();
  }
  const collections = { '/followups': 'followups', '/site-visits': 'siteVisits', '/negotiations': 'negotiations' };
  if (collections[p]) { const key = collections[p]; if (key === 'negotiations') check(sales, 'Sales access required.'); if (method === 'GET') { let rows = related(key); if (key === 'followups' && q.get('category')) { const c = q.get('category'); rows = rows.filter(r => c === 'completed' ? r.status === 'Completed' : r.status === 'Pending' && (c === 'today' ? new Date(r.scheduled_at).toDateString() === new Date().toDateString() : c === 'overdue' ? Date.parse(r.scheduled_at) < Date.now() : Date.parse(r.scheduled_at) > Date.now())); } return save({ [key]: rows }); }
    const l = get(body.leadId); check(l.assigned_user_id, 'Assign the lead first.');
    if (key === 'followups') schedule(l, body.scheduledAt, body.actionType, body.remarks);
    if (key === 'siteVisits') { check(Number.isFinite(Date.parse(body.scheduledAt)), 'Select a visit date.'); db.siteVisits.unshift({ id: uid(), lead_id: l.id, scheduled_at: body.scheduledAt, pickup_required: body.pickupRequired, remarks: body.remarks, status: 'Scheduled' }); stage(l, 'Site Visit Scheduled'); event(l, 'Visit agreed and scheduled', `${body.scheduledAt} • ${body.remarks || ''}`); }
    if (key === 'negotiations') { check(db.siteVisits.some(v => v.lead_id === l.id && v.status === 'Completed'), 'Record completed site-visit feedback first.'); check(body.quotedAmount > 0 && body.latestOffer > 0, 'Enter positive quote and offer amounts.'); check(!db.negotiations.some(n => n.lead_id === l.id && n.status === 'Active'), 'This lead already has an active negotiation.'); db.negotiations.unshift({ id: uid(), lead_id: l.id, unit_number: body.unitNumber, quoted_amount: body.quotedAmount, latest_offer: body.latestOffer, status: 'Active' }); stage(l, 'Negotiation'); event(l, 'Negotiation opened', `Offer ₹${body.latestOffer} • Unit ${body.unitNumber}`); } return save();
  }
  m = p.match(/^\/(followups|site-visits|negotiations)\/(\d+)(?:\/(complete|book))?$/);
  if (m) { const key = collections['/' + m[1]]; const r = db[key].find(r => r.id === Number(m[2])); check(r, 'Record not found.'); const l = get(r.lead_id);
    if (key === 'followups') { r.status = 'Completed'; l.next_followup_at = db.followups.find(f => f.lead_id === l.id && f.status === 'Pending')?.scheduled_at || null; event(l, 'Follow-up completed', body.remarks); }
    else if (key === 'siteVisits') { check(sales, 'A sales agent or manager records visit feedback.'); check(['Completed', 'Cancelled', 'Rescheduled'].includes(body.status) && body.feedback?.trim(), 'Choose a status and enter visit feedback.'); Object.assign(r, body); stage(l, body.status === 'Completed' ? 'Site Visit Completed' : 'Follow-up'); event(l, `Visit ${body.status}`, body.feedback); }
    else { check(sales && m[3] === 'book', 'Sales access required.'); check(r.status !== 'Closed' && body.finalAmount > 0, 'Enter a positive amount for an open deal.'); r.status = 'Closed'; db.bookings.push({ id: uid(), lead_id: l.id, final_amount: Number(body.finalAmount), booking_date: body.bookingDate || now(), unit_number: r.unit_number }); stage(l, 'Booking/Closed Won'); event(l, 'Booking confirmed', `₹${body.finalAmount} • ${body.remarks || ''}`); } return save();
  }
  if (p.startsWith('/notifications')) { const rows = db.notifications.filter(n => manager || n.user_id === actor.id); if (method !== 'GET') { rows.forEach(n => n.is_read = 1); return save(); } return save({ notifications: rows, unreadCount: rows.filter(n => !n.is_read).length }); }
  if (p === '/dashboard/summary') { const leads = db.leads.filter(visible); const ids = new Set(leads.map(l => l.id)); const fu = related('followups'); const visits = related('siteVisits'); const negs = related('negotiations'); const won = leads.filter(l => l.status === 'Won'); const today = r => new Date(r.scheduled_at).toDateString() === new Date().toDateString();
    const metrics = { totalLeads: leads.length, activeLeads: leads.filter(l => l.status === 'Active').length, newLeads: leads.filter(l => l.stage === 'New').length, wonLeads: won.length, lostLeads: leads.filter(l => l.status === 'Lost').length, totalRevenue: related('bookings').reduce((sum, b) => sum + b.final_amount, 0), overdueFU: fu.filter(f => f.status === 'Pending' && Date.parse(f.scheduled_at) < Date.now()).length, todayFU: fu.filter(f => f.status === 'Pending' && today(f)).length, todayVisits: visits.filter(today).length, siteVisits: visits.filter(v => v.status === 'Completed').length, activeNegs: negs.filter(n => n.status === 'Active').length, unassigned: leads.filter(l => !l.assigned_user_id).length };
    return save({ metrics, funnel: { total: leads.length, contacted: leads.filter(l => l.stage !== 'New').length, interested: leads.filter(l => ['Interested', 'Site Visit Scheduled', 'Site Visit Completed', 'Negotiation', 'Booking/Closed Won'].includes(l.stage)).length, siteVisits: visits.length, negotiations: negs.length, closures: won.length }, byStage: stages.map(stage => ({ stage, count: leads.filter(l => l.stage === stage).length })), bySource: db.sources.map(s => ({ source_name: s.name, count: leads.filter(l => l.source_id === s.id).length })), employeePerformance: db.users.filter(u => manager || u.id === actor.id).map(u => ({ ...safe(u), total_assigned: leads.filter(l => l.assigned_user_id === u.id).length, site_visits: visits.filter(v => get(v.lead_id).assigned_user_id === u.id).length, closures: won.filter(l => l.assigned_user_id === u.id).length })), recentActivity: db.activities.filter(a => ids.has(a.lead_id)).slice(0, 20), todayFollowupsList: fu.filter(f => f.status === 'Pending' && today(f)) });
  }
  throw new Error(`Unsupported demo action: ${p}`);
}
