import assert from 'node:assert/strict';
import { workflow } from '../src/services/workflow.js';
const memory = new Map();
globalThis.localStorage = { getItem: k => memory.get(k) ?? null, setItem: (k, v) => memory.set(k, v) };
const admin = { id: 1 }, manager = { id: 2 }, sales = { id: 3 }, caller = { id: 4 };
const request = (actor, path, method = 'GET', body = {}) => workflow(path, method, body, actor);
assert.throws(() => request(null, '/auth/login', 'POST', { email: 'admin@democrm.com', password: 'wrong' }));
assert.equal(request(null, '/auth/login', 'POST', { email: 'manager@democrm.com', password: 'Password123!' }).user.role, 'Manager');
const l = request(admin, '/leads', 'POST', { name: 'Workflow Test', phone: '9998887770', budget: 12000000 }).lead;
assert.throws(() => request(caller, `/leads/${l.id}`));
request(manager, `/leads/${l.id}/reassign`, 'POST', { assignedUserId: 4 });
assert.equal(request(caller, `/leads/${l.id}`).lead.assigned_user_id, 4);
assert.throws(() => request(caller, `/leads/${l.id}/reassign`, 'POST', { assignedUserId: 3 }));
request(caller, `/leads/${l.id}/call-outcome`, 'POST', { outcome: 'Visit declined', remarks: 'Needs another call', nextFollowupDate: new Date().toISOString() });
const f = request(caller, '/followups?category=today').followups.find(f => f.lead_id === l.id);
assert.ok(f);
request(caller, `/followups/${f.id}/complete`, 'PUT');
assert.ok(request(caller, '/followups?category=completed').followups.some(row => row.id === f.id));
request(caller, `/leads/${l.id}/call-outcome`, 'POST', { outcome: 'Visit agreed', remarks: 'Saturday confirmed' });
request(caller, '/site-visits', 'POST', { leadId: l.id, scheduledAt: new Date().toISOString(), remarks: 'Show 3BHK' });
request(admin, `/leads/${l.id}/reassign`, 'POST', { assignedUserId: 3 });
assert.throws(() => request(caller, `/leads/${l.id}`));
const visit = request(sales, `/leads/${l.id}`).siteVisits[0];
assert.throws(() => request(sales, '/negotiations', 'POST', { leadId: l.id, quotedAmount: 12000000, latestOffer: 11000000 }));
request(sales, `/site-visits/${visit.id}`, 'PUT', { status: 'Completed', feedback: 'Likes the unit; discussing price' });
request(sales, '/negotiations', 'POST', { leadId: l.id, unitNumber: 'A-101', quotedAmount: 12000000, latestOffer: 11000000 });
const deal = request(sales, `/leads/${l.id}`).negotiations[0];
request(sales, `/negotiations/${deal.id}/book`, 'POST', { finalAmount: 11500000 });
assert.throws(() => request(sales, `/negotiations/${deal.id}/book`, 'POST', { finalAmount: 11500000 }));
const result = request(admin, `/leads/${l.id}`);
assert.equal(result.lead.stage, 'Booking/Closed Won');
assert.equal(result.bookings[0].final_amount, 11500000);
assert.ok(result.activities.length >= 8);
assert.equal(request(admin, '/dashboard/summary').metrics.totalRevenue, 11500000);
assert.equal(request(caller, '/dashboard/summary').metrics.totalRevenue, 0);
assert.throws(() => request(caller, '/settings/company'));
console.log('PASS: login, role isolation, assignment, decline/follow-up, visit consent, handover, visit feedback, negotiation, booking, timeline and revenue.');
